name: peepee
description: "Un petit pipi, une grande dÃ©livrance !"
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5
  get_it: ^9.2.0

  # Map
  maplibre_gl: ^0.24.1

  # Device & System
  wakelock_plus: ^1.3.3
  connectivity_plus: ^7.0.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  
  # Networking
  dio: ^5.9.0

  # Clustering
  fluster: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code quality & analysis
  flutter_lints: ^4.0.0

  # App assets generation
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.1

# Configuration for the native splash screen
flutter_native_splash:
  color: "#A5CCCA"
  image: assets/images/splashPeePee.png
  android_12:
    image: assets/images/splashPeePee.png
    icon_background_color: "#A5CCCA"
  web: false

# Configuration for the launcher icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/IconPeePee.png"
  remove_alpha_channel_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/toiletPin.png
    - assets/images/toiletPinSelected.png
    - assets/images/urgentPin.png

  fonts:
    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

